### ISSUE TITLE
Запрос авторизации

### ISSUE THREAD

**Issue by eX3emz** [lizardsystems/hass-taipit#2]
Периодически возникает запрос "Необходимо реконфигурация интеграции". Требуется пароль от ЛК Тайпит. После ввода пароля, после этого всё работает но возникают пробелы в данных.
![image](https://github.com/lizardsystems/hass-taipit/assets/60067406/78553aa0-af15-4aa7-a1cc-e0c99bb60a38)

**Comment by vzagorovskiy** [comment]
У меня такое случилось только когда интернет отвалился на несколько часов. А так пару месяцев работало исправно.
Включите, пожалуйста, лог и пришлите его сюда

Включите ведение журнала отладки, поместив следующие инструкции в файл configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.taipit: debug
    aiotaipit: debug
```
